import { MediaSort } from 'src/providers/anilist/graphql/types/MediaEnums';

export class ReleaseFilter {
  constructor(
    public sort?: MediaSort[],
    public perPage?: number,
    public page?: number,
    public sourceIn?: any,
    public popularityLesser?: number,
    public popularityGreater?: number,
    public popularityNot?: number,
    public averageScoreLesser?: number,
    public averageScoreGreater?: number,
    public averageScoreNot?: number,
    public licensedByIdIn?: any,
    public licensedByIn?: any,
    public tagCategoryNotIn?: any,
    public tagCategoryIn?: any,
    public tagNotIn?: any,
    public tagIn?: any,
    public genreNotIn?: any,
    public genreIn?: any,
    public durationLesser?: number,
    public durationGreater?: number,
    public episodesLesser?: number,
    public episodesGreater?: number,
    public statusNotIn?: any,
    public statusNot?: any,
    public statusIn?: any,
    public formatNotIn?: any,
    public formatNot?: any,
    public formatIn?: any,
    public endDateLike?: string,
    public endDateLesser?: string,
    public endDateGreater?: string,
    public startDateLike?: string,
    public startDateLesser?: string,
    public startDateGreater?: string,
    public idMalNotIn?: any,
    public idMalIn?: any,
    public idMalNot?: number,
    public idNotIn?: any,
    public idIn?: any,
    public idNot?: number,
    public search?: string,
    public isLicensed?: boolean,
    public countryOfOrigin?: string,
    public isAdult?: boolean,
    public format?: any,
    public type?: any,
    public status?: any,
    public season?: any,
    public id?: number,
    public idMal?: number,
  ) {}
}
