-- AlterTable
ALTER TABLE "User" ALTER COLUMN "status" SET DEFAULT 'ACTIVE',
ALTER COLUMN "reputation" SET DEFAULT 100.0,
ALTER COLUMN "isOnline" SET DEFAULT false,
ALTER COLUMN "lastSeen" SET DEFAULT CURRENT_TIMESTAMP;
